id: A92CA6F2A
title: 'Nectar Shower of Blessings: A Song of Yearning Devotion Recalling the Everpresent
  Gurus'
type: translation
pechas:
- IDF5D8028
- I62FE0754
- IE28A42E1
- I50447501
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:09:19.065783
  last_modified_at: 2023-01-04 12:09:19.065793
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IDF5D8028/C9F5: '3151'
  I62FE0754/6DBB: '3151'
  IE28A42E1/5D2C: '3151'
  I50447501/F64F: '3151'
